version: '3.7'

services:
  app:
    image: matomo:3.13.5
    restart: always
    volumes:
      - matomo:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: db
    ports:
      - 8090:80
    depends_on:
      - db

  db:
    image: mariadb:10.5.2
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - matomo.env

volumes:
  db:
  matomo: